# Generated by Django 5.2.14 on 2026-05-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='retry_count',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='retry_delay',
            field=models.IntegerField(default=5),
        ),
    ]
