# Generated by Django 5.2.14 on 2026-05-06 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
                ('semester', models.IntegerField()),
                ('subject_credits', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='reports/excel/')),
                ('chart_image', models.ImageField(upload_to='reports/charts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='scraper.scrapejob')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scraper.scrapejob')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSGPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyzer.analysisreport')),
                ('student_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.studentresult')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('is_backlog', models.BooleanField(default=False)),
                ('internal_marks', models.IntegerField(blank=True, null=True)),
                ('external_marks', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(choices=[('P', 'Pass'), ('F', 'Fail'), ('A', 'Absent'), ('W', 'Withheld'), ('NE', 'Not Eligible')], max_length=2)),
                ('announced_on', models.DateField(blank=True, null=True)),
                ('old_result', models.CharField(blank=True, choices=[('P', 'Pass'), ('F', 'Fail'), ('A', 'Absent'), ('W', 'Withheld'), ('NE', 'Not Eligible')], max_length=2)),
                ('reval_marks', models.IntegerField(blank=True, null=True)),
                ('reval_result', models.CharField(blank=True, choices=[('P', 'Pass'), ('F', 'Fail'), ('A', 'Absent'), ('W', 'Withheld'), ('NE', 'Not Eligible')], max_length=2)),
                ('student_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.studentresult')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeared', models.IntegerField()),
                ('passed', models.IntegerField()),
                ('failed', models.IntegerField()),
                ('absent', models.IntegerField()),
                ('withheld', models.IntegerField()),
                ('not_eligible', models.IntegerField()),
                ('pass_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyzer.analysisreport')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.subject')),
            ],
        ),
    ]
