# Generated by Django 5.2.14 on 2026-05-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
        ('scraper', '0002_scrapejob_retry_count_scrapejob_retry_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='chart_image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/charts/'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/excel/'),
        ),
        migrations.AlterUniqueTogether(
            name='studentresult',
            unique_together={('job', 'usn')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectmark',
            unique_together={('student_result', 'subject', 'semester')},
        ),
    ]
