# Generated by Django 5.2.14 on 2026-05-12 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_analysisreport_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectstats',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.analysisreport'),
        ),
        migrations.AlterUniqueTogether(
            name='studentsgpa',
            unique_together={('report', 'student_result')},
        ),
    ]
