# Generated by Django 5.2.14 on 2026-05-12 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_alter_subjectstats_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsgpa',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.analysisreport'),
        ),
    ]
